install request and add mapOperations.js, mapOperations.test.js, getAlbumById.js, getAlbumById.test.js
Reference :

https://stackabuse.com/using-spies-for-testing-in-javascript-with-sinon/

https://www.npmjs.com/package/request

Error :

PS C:\Users\Han\Desktop\code\mocha-example> npx mocha .\test\getAlbumById.test.js

ReferenceError: regeneratorRuntime is not defined
    at C:\Users\Han\Desktop\code\mocha-example\src\/getAlbumById.js:12:17
    at Object.<anonymous> (C:\Users\Han\Desktop\code\mocha-example\src\/getAlbumById.js:12:17)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module._compile (C:\Users\Han\Desktop\code\mocha-example\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.newLoader [as .js] (C:\Users\Han\Desktop\code\mocha-example\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (C:\Users\Han\Desktop\code\mocha-example\test\/getAlbumById.test.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Module._compile (C:\Users\Han\Desktop\code\mocha-example\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Object.newLoader [as .js] (C:\Users\Han\Desktop\code\mocha-example\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.exports.requireOrImport (C:\Users\Han\Desktop\code\mocha-example\node_modules\mocha\lib\esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (C:\Users\Han\Desktop\code\mocha-example\node_modules\mocha\lib\esm-utils.js:33:34)
    at Mocha.loadFilesAsync (C:\Users\Han\Desktop\code\mocha-example\node_modules\mocha\lib\mocha.js:427:19)
    at singleRun (C:\Users\Han\Desktop\code\mocha-example\node_modules\mocha\lib\cli\run-helpers.js:156:15)
    at exports.runMocha (C:\Users\Han\Desktop\code\mocha-example\node_modules\mocha\lib\cli\run-helpers.js:225:10)
    at Object.exports.handler (C:\Users\Han\Desktop\code\mocha-example\node_modules\mocha\lib\cli\run.js:366:11)
    at C:\Users\Han\Desktop\code\mocha-example\node_modules\yargs\lib\command.js:241:49
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
PS C:\Users\Han\Desktop\code\mocha-example>

Solution :

https://github.com/babel/babel/issues/8829

https://github.com/liferay/liferay-npm-tools/issues/105

My solution :

C:\Users\Han\Desktop\code\mocha-example\babel.config.js

module.exports = {
  presets: [
    [
      '@babel/preset-env',
      {
        targets: {
          node: 'current',
        },
      },
    ],
  ],
};